# HTTP Config
server:  port: 6785
  
# Spring Config
spring:  application:    name: api-gateway
  cloud:    gateway:      discovery:        locator:          enabled: true
          lower-case-service-id: true
    
# Eureka Config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/      